# Generated by Django 2.2.5 on 2019-10-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
