# Generated by Django 2.2.5 on 2019-10-14 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import openwisp_users.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_users', '0007_unique_email'),
        ('testapp', '0005_auto_20191014_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('IP', models.CharField(max_length=64, verbose_name='IP Address')),
                ('MAC', models.CharField(max_length=64, verbose_name='MAC Address')),
                ('is_active', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openwisp_users.Organization', verbose_name='organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(openwisp_users.mixins.ValidateOrgMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='organization',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='is_active',
            new_name='is_online',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Shelf',
        ),
        migrations.AddField(
            model_name='consumer',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Device'),
        ),
    ]
