# Generated by Django 2.0.13 on 2019-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_importlogfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='LogFile')),
                ('FileName', models.CharField(max_length=50, verbose_name='file name')),
            ],
            options={
                'ordering': ['FileName'],
            },
        ),
        migrations.DeleteModel(
            name='ImportLogFiles',
        ),
    ]
