# Generated by Django 2.0.13 on 2019-10-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20191016_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportFiles',
        ),
    ]
