# Generated by Django 2.0.13 on 2019-10-25 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_delete_importfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Device'),
        ),
    ]
